### ISSUE TITLE
Hole is not centered for M20x1.5

### ISSUE THREAD

**Issue by amadeuspzs** [rcolyer/threads-scad#5]
1. Manually update `function ThreadPitch(diameter) =` to have `      [20, 1.5],`
2. Run `MetricNut(20, thickness=5, tolerance=0.75);`

Hole is not centered:

![image](https://user-images.githubusercontent.com/534681/142286910-ace7085c-1663-45ed-a0ef-9aece90d0092.png)
![image](https://user-images.githubusercontent.com/534681/142286938-722601f0-af73-449f-a2d4-023c657c6138.png)

**Comment by sfoster** [comment]
I'm seeing the same on every size I've tried to far. 
I was able to fudge it with translate([0.5. 0.25, 0]) to get a 10mm ScrewThread reasonable well centered, but I'm afraid I don't know the significance of these offsets or how they are proportional to which parameters.

**Comment by rcolyer** [comment]
This is not a bug, and it's not off-center.  It's math.  Every thread does this, because the thread cut-out is basically spiraling around the middle of the axis along the path, so when you get to the end the cross-section of the true thread shape with the top surface will always be some part of this spiraling shape, and not a cylinder.  Machined nuts resolve the aesthetics of this by a secondary step of chamfering the hole, which you can do here as well by differencing out a cone (cylinder with two radii).  If you look closely at any machined nut you will see this.  Given that the screw holes for this library are general purpose it did not seem appropriate to hard code this chamfering cut-out into the screw hole itself (e.g., should it be on one side?  both sides?  no sides for the case of a different recessed hole?), but it is left as a user option to add on externally since it is very straightforward in OpenSCAD.

To evaluate centering, you should not be looking at the top or bottom surfaces, but should be looking through the hole, and check the centering of the farthest in portion of the threads for the hole, which will intersect the full spiraling shape of the thread.  (Which was checked meticulously during initial implementation.)

**Comment by sfoster** [comment]
> This is not a bug, and it's not off-center. It's math. 

Yeah I came back to apologize as I realized the same once I had the part printed out. Sorry for the noise.
