### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by jandrieu** [rcolyer/threads-scad#9]
This is a great library. Thank you for the effort.

I was wondering if you could you provide some examples.

Even just sharing the scad file that generated the demo STL would be helpful.

**Comment by rcolyer** [comment]
threads.scad already contains the demo generating code, at the bottom in the Demo module.  If you open threads.scad directly instead of doing a "use" of it, it will produce the demo.

**Comment by PennRobotics** [comment]
Nowhere in the demo is the keyword `use` used, so you're relying on users knowing the difference between `use` and `include` (which is going to be tricky for beginners since `include` is the method to automatically run the demo).

Sure, it's one of the smallest conceptual leaps&mdash;almost deserving of a &ldquo;RTFM&rdquo; response&mdash;but you already have an issue (this, one of only six) and a separate PR (#8) showing users are stumbling while using your library. (Not every user of yours is mapping Utah array outputs to episodic memories as their day job[^1]; some of us simpletons need proper hand-holding!)

[^1]: BTW, if you know/see him around, say hi to Brian Litt from one of Katherine&rsquo;s advisees who took his course. BCI was one of the best taught and most interesting classes at Penn a decade ago.

It takes less time than my comment here to add a line at the top of **README.md**, something like

````md
## Quick start

```text
use <threads.scad>
Demo();
MetricBoltSet(3, 8);
```
````

(I repeated the top bolt line from the demo to illustrate that any module from the library can be run, because you'd otherwise have to explain to a few confused users that they _still_ don&rsquo;t need to modify **threads.scad** itself.)
